SELECT A.BG, (A.ACP - B.DN) AS BLOOD_NEEDED FROM 
(SELECT BG, SUM(AMOUNT) AS ACP FROM ACCEPTOR GROUP BY BG) A JOIN
(SELECT BG, SUM(AMOUNT) AS DN FROM DONOR GROUP BY BG ) B ON A.BG = B.BG
WHERE (A.ACP - B.DN) > 0
ORDER BY A.BG
